#ifndef _CONFIG_H_
#define _CONFIG_H_

#define CONFIG_CIFS_SMB2 1
#define CONFIG_CIFS 1
#define CONFIG_CIFS_STATS 1
#define CONFIG_CIFS_UPCALL 1
#define CONFIG_CIFS_XATTR 1
#define CONFIG_CIFS_POSIX 1
#define CONFIG_CIFS_ACL 1
#define CONFIG_CIFS_DEBUG 1
#define CONFIG_CIFS_DFS_UPCALL 1
#define CONFIG_CIFS_SMB311 1
#define CONFIG_CIFS_FSCACHE 1

#endif